version: "3.3"

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tmp/postgres-data:/var/lib/postgresql/data
  back:
    build: back/
    restart: unless-stopped
    command: sh -c "/wait &&  npm run db:create 'CREATE DATABASE fetc;' && npm run db:refresh && npm run start"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
  front:
    build: front/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - back
  copilote_notes:
    build: copilot/note_system
    ports:
      - "9990:9990"

volumes:
  front:
