version: "3.9"
services:
  front:
    build: front/
    ports:
      - "8000:8000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=8000
    volumes:
      - ./front:/app
    depends_on:
      - back
  back:
    build: back/
    ports:
      - "3000:3000"
volumes:
  front:
