version: "3.3"

services:
    db:
        image: postgres
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - ./.init.sql:/docker-entrypoint-initdb.d/init.sql
            - db:/var/lib/postgresql/data

    back:
        build: back/
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - HOST=0.0.0.0
        depends_on:
            - db
        links:
            - db
        ports:
            - "3000:3000"

    front:
        build: front/
        restart: unless-stopped
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - DOCKER=1
        depends_on:
            - back
        links:
            - back

volumes:
    db:
        driver: local
