name: CD with dockerhub to virtual private server

on:
  push:
    branches: [features_continue_deploiement, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: fichesetchips
        password: saucissegalactique34
        
    - name: Build image client
      run: docker build front/. --no-cache --build-arg BACK_HOST_ARG=54.38.185.154 --build-arg BACK_PORT_ARG=3000 -t client:new_image

    - name: Build image server
      run: docker build back/. -t server:new_image

    - name: tags
      run: docker tag client:new_image fichesetchips/client:latest

    - name: tags
      run: docker tag server:new_image fichesetchips/server:latest

    - name: push client 1
      run: docker push fichesetchips/client:latest

    - name: push server 1
      run: docker push fichesetchips/server:latest
      
    - name: Deploy client
      uses: appleboy/ssh-action@master
      with:
        host: 54.38.185.154
        username: epitech
        password: onepiececestlameilleureserie
        script:
          # docker rmi $(docker images -a -q) --force &&
          docker rm $(docker ps -a -q) --force &&
          docker pull fichesetchips/client:latest &&
          docker pull fichesetchips/server:latest &&
          docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES=54.38.185.154 -e POSTGRES_DB=fichesetchips -p 5432:5432 postgres:latest &&
          docker run -d -p 3000:3000 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=fichesetchips -e DB_HOST=54.38.185.154 fichesetchips/server:latest &&
          docker run -d -p 80:8000 -e NUXT_HOST=0.0.0.0 -e NUXT_PORT=8000 -e BACK_HOST=54.38.185.154 -e BACK_PORT=3000 fichesetchips/client:latest 
